### ISSUE TITLE
AltJit and wifi sync doesn't work with AUR 

### ISSUE THREAD

**Issue by MrArdillo** [altlinux-team/AltLinux#7] opened 2022-10-17 20:05 UTC
I'm using ArcoLinux with the AUR version

**Comment by maxasix** [comment] 2022-10-19 08:57
Duplicate of #5

**Closed** 2022-10-19 08:58 UTC

**Comment by MrArdillo** [comment] 2022-10-19 09:04
Can you package that together with the AUR version to full functionality?

**Comment by maxasix** [comment] 2022-10-25 10:20
Not how it works

**Comment by MrArdillo** [comment] 2022-10-25 13:59
Okay, but can you make a tutorial in the description of the git for knowing how to configure it please?

**Comment by maxasix** [comment] 2022-10-25 16:24
If you have a tutorial then I'd be glad to add it.

**Comment by MrArdillo** [comment] 2022-10-29 17:39
In their repository they put this

Install usbmuxd for your distribution
Download netmuxd from the releases and place it somewhere permanent
Install screen and open run a new screen like so screen -S netmuxd
Run netmuxd like ./netmuxd --disable-unix --host 127.0.0.1, then press control a+d to escape the screen
Start a new screen for AltServer like screen -S altserver
Set the environment variable like export USBMUXD_SOCKET_ADDRESS=127.0.0.1:27015
Run AltServer ./AltServer-x86_64
